name: Deploy to GitHub Pages

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          
      - run: git checkout dev
      - run: npm install
      
      - name: Configure git
        run: |
          git config user.name "[bot] gh-action deploy"
          git config user.email "1296845690@qq.com"
          
      - name: Build
        run: |
          set -e
          npm run build
          
      - name: Deploy
        env:
          GHP_REPO: github.com/fduhole/fduhole.github.io
          GPA_TOKEN:  ${{ secrets.GPA_TOKEN }}
        run: |
          cd dist
          git init
          git add -A
          git commit -m 'gh-action deploy'
          git push -f "https://${GPA_TOKEN}@${GHP_REPO}" HEAD:main
