name: Deploy to GitHub Pages

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - run: git checkout dev
      - run: npm ci

      - name: Configure git
        run: |
          git config user.name "dest1n1s"
          git config user.email "648377563@qq.com"

      - name: Build (With Report)
        run: |
          set -e
          npm run build-report

      - name: Deploy
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          cd dist
          git init
          git add -A
          git commit -m 'gh-action deploy'
          git push -f "https://${TOKEN}@github.com/OpenTreeHole/vue.git" HEAD:gh-page
